export enum StatusPersonalLoan {
  MOUNTHLY_BUDGET = 'MOUNTHLY_BUDGET',
  TEMRS_LOAN = 'TEMRS_LOAN',
  ASSETS = 'ASSETS',
  TC = 'TC',
  CREATED = 'CREATED',
  IN_PROCESS = 'IN_PROCESS',
  FAILED = 'FAILED',
}
